name: AugmentedVoid
version: '${project.version}'
main: com.augmentedvoid.AugmentedVoidPlugin
api-version: '1.21'
author: YourName
description: Adds Augmented Void potion with dragon head mechanics

commands:
  augmentedvoid:
    description: Main plugin command
    usage: /<command>
    permission: augmentedvoid.admin
    permission-message: You don't have permission to use this command.
  userability:
    description: Use void ability
    usage: /<command> <1>
    permission-message: You don't have permission to use this command.
  userdrain:
    description: Drain void effect back into potion
    usage: /<command> <1>
    permission-message: You don't have permission to use this command.

permissions:
  augmentedvoid.admin:
    description: Allows use of admin commands
    default: op